name: scan image with trivy
on: 
 workflow_dispatch: 
   inputs:
      image_name:
        description: 'Image name with tag which needs to be scanned'
        required: true
        default: ''
      docker_username:
        description: 'In case image is private provide username, in case of public leave it blank'
        required: false
        default: ''
      docker_password:
        description: 'In case image is private provide password, in case of public leave it blank'
        required: false
        default: ''
jobs:
  script:
    runs-on:
      - ubuntu-latest
    name: pull image 
    steps:
      - name: export, build and push
        env: 
           docker_pass: ${{secrets.docker_pass}}
        run: |
           if [ -n "${{ github.event.inputs.docker_username }}" ] && [ -n "${{ github.event.inputs.docker_password }}" ]; then
            docker login -u '${{ github.event.inputs.docker_username }}' -p '${{ github.event.inputs.docker_password }}'
           fi
           docker pull ${{ github.event.inputs.image_name }}

      - name: ☢ Image Scan
        uses: aquasecurity/trivy-action@master
        id: scan
        with:
          image-ref: '${{ github.event.inputs.image_name }}'
          format: 'template'
          template: "@/contrib/html.tpl"
          output: 'trivy-image-results.html'
          exit-code: '0'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
      
      - name: ⬆ Upload Trivy Image scan results
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Trivy Scan HTML Report
          path: trivy-image-results.html
           
